### ISSUE TITLE
Maan you are hard to contact! :P

### ISSUE THREAD

**Issue by Gamewise** [maanlamp/maanlamp#2]
Hey mate, sorry about posting an issue here... I couldn't work out how to contact you...

I came across some awesome code you wrote (I think?) on stack exchange for preloading images:
`const preload = src => new Promise(function(resolve, reject) {
  const img = new Image();
  img.onload = function() {
    resolve(img);
  }
  img.onerror = reject;
  img.src = src;
});

const preloadAll = sources =>
  Promise.all(
    sources.map(
      preload));

const sources = [
etc....`

I tried it out and it's exactly what I was after -> I was wondering if I'm allowed to use this code in a project I'm working on? 

No pressure or anything, just thought I'd ask :)

Thanks so much for considering it,

Gil

**Comment by maanlamp** [comment]
Oh I've only just seen this issue, I hope my response isn't too late. I think a comment on the answer in question would probably have been easier, but I don't mind you asking here.

I think snippets on Stack Exchange are in the public domain, so you're absolutely free to use it regardless of my approval, no attribution required. That being said, you have my blessing.

**Comment by Gamewise** [comment]
Ahhhh thanks so much!

I did try to comment on stack exchange but newcomers aren't allowed to
comment apparently... 😥

Thanks maanlamp!
